Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -28,27 +28,9 @@ steps:
         echo $status
         echo "Quality gate status: $status"
         if [ "$status" != "OK" ]; then
-        echo "Quality gate failed"
-        exit 1
-      fi
- 
-  #   entrypoint: 'bash'
-  #   args:
-  #     - '-c'
-  #     - |
-  #       apt-get update && apt-get install -y curl
-  #       apt-get install -y jq
-  #       _QUALITY_GATE_STATUS=$(curl -s -H "Authorization: Basic $(echo -n "$$SONAR_TOKEN:" | base64)" https://sonarcloud.io/api/qualitygates/project_status?projectKey=workspace1101_testinggcp | jq -r '.projectStatus.status')
-
-  #       # _QUALITY_GATE_STATUS=$(curl -v -G -u $$_SONAR_TOKEN: https://sonarcloud.io/web_api/api/qualitygates/project_status?projectKey=workspace1101_testinggcp)
-  #       # _QUALITY_GATE_STATUS=$(curl -s -G -u $$_SONAR_TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=workspace1101_testinggcp)
-  #       echo _QUALITY_GATE_STATUS
-  #       if [ "$_QUALITY_GATE_STATUS" != "OK" ]; then
-  #         echo "Quality gate is not OK: $_QUALITY_GATE_STATUS"
-  #         exit 1
-  #       fi
-  #       # https://sonarcloud.io/web_api/api/qualitygates/project_status?deprecated=false&section=params
-        
+          echo "Quality gate failed"
+          exit 1
+        fi
 availableSecrets:
   secretManager:
   - versionName: projects/364895990307/secrets/sonarcloud-token/versions/2
